import Anthropic from '@anthropic-ai/sdk'
import type { Issue } from '@/lib/scan/phase2'

// ─── Tunables ──────────────────────────────────────────────────────────

const REPORT_MODEL = 'claude-sonnet-4-6'
const REPORT_MAX_TOKENS = 2_000
const REPORT_TEMPERATURE = 0  // deterministic — same scan inputs → same report

// At >50 issues we stop sending the full issue array and pass only a
// category breakdown plus the pre-sorted solution candidates. The
// solution candidates ARE the actionable subset, so Claude still gets
// enough detail to write the report — we just trim the long tail of
// low-priority warnings that bloat the token count.
const ISSUE_FULL_LIMIT = 50

// Solution map cap. Owners can't act on more than ~15 prioritised
// items; anything past that is decoration. The pre-sort cap and
// post-process cap match so Claude can't expand beyond what the seed
// allows without explicitly merging items.
const SOLUTION_MAP_MAX = 15

// ─── System prompt ─────────────────────────────────────────────────────
//
// Mirrored from CLAUDE.md "Claude Report Prompt Pattern" with:
//   - "Never fabricate findings" rule (CLAUDE.md updated to match)
//   - Full 7-category list (DB schema, not the abridged 4)
//   - Removed `issues` from the requested output shape — we keep our
//     own pre-built issues and only ask Claude for summary +
//     health_score + solution_map (see buildOutputSchema notes)

const SYSTEM_PROMPT = `You are a website health analyst writing for non-technical Indian business owners.

Rules:
- Plain language only. No jargon.
- Each finding: one sentence explaining the problem, one sentence on impact, one sentence on exact action.
- Solution map: ordered by priority (High first) then effort (Low first).
- Priority: High = affects customers reaching the business. Medium = affects trust. Low = affects SEO/polish.
- Effort: Low = owner or developer fixes in under 1 hour. Medium = under 1 day. High = needs planning.
- Never use words: "utilize", "leverage", "ensure", "robust", "seamless".
- If you cannot determine an appropriate finding for a check result, omit it entirely. Never fabricate findings.
- Output: valid JSON only. No markdown. No preamble.`

// ─── Public types ──────────────────────────────────────────────────────

export type ReportPhase1Snapshot = {
  url: string
  pageCount: number
  tier: string
  ssl: { basicValid: boolean; detail: string }
  phoneCount: number
  emailCount: number
}

export type ReportIntake = {
  text?: string | null
  cards?: string[] | null
}

export type ReportInput = {
  url: string
  phase1: ReportPhase1Snapshot
  issues: Issue[]
  intake?: ReportIntake | null
}

export type SolutionStep = {
  order: number
  title: string
  body: string
  priority: 'high' | 'medium' | 'low'
  effort: 'low' | 'medium' | 'high'
}

export type ReportOutput = {
  health_score: number
  summary: string
  solution_map: SolutionStep[]
}

// ─── Public entry point ────────────────────────────────────────────────

/**
 * Generate the Claude-authored portion of the report: health_score,
 * one-sentence summary, and ordered solution_map.
 *
 * Issues themselves are NOT regenerated by Claude. Phase 2's check
 * modules built each issue with real contextual data (phone numbers,
 * URLs, expiry days, page paths) — letting Claude rewrite those would
 * risk hallucination, and the "never fabricate findings" rule says
 * exactly that. Claude's role is the analyst layer on top of facts the
 * scan already established.
 *
 * Returns `null` on:
 *   - Missing API key
 *   - Two consecutive parse failures (initial + strict-reminder retry)
 *   - Validation failure on the parsed shape
 *   - Network / API error
 *
 * On null, the orchestrator falls back to the heuristic health_score
 * and a generic summary; issues are unaffected.
 */
export async function generateReport(
  input: ReportInput,
): Promise<ReportOutput | null> {
  const apiKey = process.env.ANTHROPIC_API_KEY
  if (!apiKey) {
    console.warn(
      '[claude/report] ANTHROPIC_API_KEY missing — skipping Claude report',
    )
    return null
  }

  const client = new Anthropic({ apiKey })
  const userPrompt = buildUserPrompt(input)

  // Attempt 1
  const first = await callClaude(client, userPrompt)
  if (first) {
    const finalized = finalizeReport(first)
    if (finalized) return finalized
  }

  // Attempt 2 — strict reminder on the SAME prompt. Temperature is
  // already 0 so the model output is deterministic; the reminder is
  // a regeneration nudge for the rare case where Claude wrapped the
  // JSON in markdown despite the rule.
  const strict =
    userPrompt +
    '\n\n## Reminder\nReturn ONLY valid JSON. No markdown fences. No explanatory text. Start the response with `{` and end with `}`.'
  const second = await callClaude(client, strict)
  if (second) {
    const finalized = finalizeReport(second)
    if (finalized) return finalized
  }

  console.error('[claude/report] failed to obtain valid JSON after retry')
  return null
}

// ─── Claude call ───────────────────────────────────────────────────────

async function callClaude(
  client: Anthropic,
  userPrompt: string,
): Promise<unknown | null> {
  let res: Anthropic.Messages.Message
  try {
    res = await client.messages.create({
      model: REPORT_MODEL,
      max_tokens: REPORT_MAX_TOKENS,
      temperature: REPORT_TEMPERATURE,
      system: SYSTEM_PROMPT,
      messages: [{ role: 'user', content: userPrompt }],
    })
  } catch (err) {
    console.error(
      '[claude/report] API call failed',
      err instanceof Error ? err.message : err,
    )
    return null
  }

  const block = res.content[0]
  if (!block || block.type !== 'text') return null
  const raw = block.text.trim()
  if (!raw) return null

  // Tolerate a markdown fence even though the prompt forbids it. Claude
  // occasionally wraps JSON in ```json ... ``` despite instructions; the
  // strict-reminder retry above handles the edge case where this slips
  // past the rule, but stripping here means the first call usually
  // succeeds even if it does fence.
  const stripped = stripMarkdownFences(raw)
  try {
    return JSON.parse(stripped)
  } catch {
    console.warn(
      '[claude/report] JSON.parse failed on response (truncated):',
      stripped.slice(0, 200),
    )
    return null
  }
}

function stripMarkdownFences(text: string): string {
  const m = text.match(/^```(?:json)?\s*\n?([\s\S]*?)\n?```\s*$/)
  if (m && m[1]) return m[1].trim()
  return text
}

// ─── User prompt construction ──────────────────────────────────────────

function buildUserPrompt(input: ReportInput): string {
  const parts: string[] = []
  const intakeBlock = buildIntakeBlock(input.intake)
  if (intakeBlock) parts.push(intakeBlock)
  parts.push(buildPhase1Block(input.phase1))
  parts.push(buildIssuesBlock(input.issues))
  parts.push(buildSolutionSeedBlock(input.issues))
  parts.push(buildOutputSchemaBlock())
  return parts.join('\n\n')
}

function buildIntakeBlock(intake: ReportIntake | null | undefined): string | null {
  if (!intake) return null
  const text = intake.text?.trim()
  const cards = intake.cards?.filter(Boolean) ?? []
  if (!text && cards.length === 0) return null

  const lines = ['## Owner intake (plain-language goals — written by the site owner)']
  if (cards.length > 0) {
    lines.push(`Selected concerns: ${cards.join(', ')}`)
  }
  if (text) {
    // Owner text may be in any language (Hindi, Gujarati, English, mix).
    // Claude detects language automatically per CLAUDE.md rule 52.
    lines.push(`Owner's own words: ${text}`)
  }
  return lines.join('\n')
}

function buildPhase1Block(p: ReportPhase1Snapshot): string {
  return [
    '## Site context',
    `URL: ${p.url}`,
    `Pages estimated: ${p.pageCount}`,
    `Tier: ${p.tier}`,
    `SSL: ${p.ssl.basicValid ? 'valid' : 'missing'} — ${p.ssl.detail}`,
    `Phone numbers found on homepage: ${p.phoneCount}`,
    `Email addresses found on homepage: ${p.emailCount}`,
  ].join('\n')
}

function buildIssuesBlock(issues: Issue[]): string {
  if (issues.length === 0) {
    return '## Findings\nNo issues found by the scan.'
  }
  if (issues.length <= ISSUE_FULL_LIMIT) {
    return `## Findings (${issues.length} total)\n${JSON.stringify(issues, null, 2)}`
  }
  // >50 — pass category breakdown only; the solution-seed block below
  // carries the actionable top items, so Claude still has detail to
  // work from without bloating the prompt.
  const breakdown = summariseByCategory(issues)
  return `## Findings (${issues.length} total — full list omitted, category breakdown only)
${breakdown}

The actionable top items appear in the next section.`
}

function summariseByCategory(issues: Issue[]): string {
  const buckets: Record<string, { fail: number; warning: number; ok: number }> = {}
  for (const i of issues) {
    if (!buckets[i.category]) {
      buckets[i.category] = { fail: 0, warning: 0, ok: 0 }
    }
    if (i.status === 'fail') buckets[i.category]!.fail += 1
    else if (i.status === 'warning') buckets[i.category]!.warning += 1
    else buckets[i.category]!.ok += 1
  }
  return Object.entries(buckets)
    .map(([cat, c]) => {
      const parts: string[] = []
      if (c.fail) parts.push(`${c.fail} fail`)
      if (c.warning) parts.push(`${c.warning} warning`)
      if (c.ok) parts.push(`${c.ok} ok`)
      return `- ${cat}: ${parts.join(', ')}`
    })
    .join('\n')
}

function buildSolutionSeedBlock(issues: Issue[]): string {
  // Server-side pre-sort: priority desc, effort asc, status (fail before
  // warning). Claude's job is to confirm/refine — not re-sort from
  // scratch — and the seed gives it a clear ranking to anchor on.
  const seeded = sortIssues(issues).slice(0, SOLUTION_MAP_MAX)
  if (seeded.length === 0) {
    return '## Pre-sorted solution candidates\n(none — no actionable issues)'
  }
  const seed = seeded.map((i, idx) => ({
    order: idx + 1,
    title: shorten(i.item, 60),
    body: i.action,
    priority: i.priority,
    effort: i.effort,
    category: i.category,
  }))
  return `## Pre-sorted solution candidates (high priority + low effort first)
This list is already ordered. Confirm the order is right, merge near-duplicates if any, and refine the wording. Do NOT re-sort from scratch. You may drop items that don't meaningfully help the owner; you may not invent new ones.

${JSON.stringify(seed, null, 2)}`
}

function shorten(s: string, max: number): string {
  if (s.length <= max) return s
  return s.slice(0, max - 1) + '…'
}

function sortIssues(issues: Issue[]): Issue[] {
  const statusRank = { fail: 0, warning: 1, ok: 2 } as const
  const priorityRank = { high: 0, medium: 1, low: 2 } as const
  const effortRank = { low: 0, medium: 1, high: 2 } as const
  return [...issues].sort((a, b) => {
    const sa = statusRank[a.status]
    const sb = statusRank[b.status]
    if (sa !== sb) return sa - sb
    const pa = priorityRank[a.priority]
    const pb = priorityRank[b.priority]
    if (pa !== pb) return pa - pb
    return effortRank[a.effort] - effortRank[b.effort]
  })
}

function buildOutputSchemaBlock(): string {
  return `## Output schema
Return JSON in this exact shape (no markdown, no preamble, no \`\`\` fences):
{
  "health_score": number (0-100, integer),
  "summary": string (one sentence describing the site's overall health and the top concern),
  "solution_map": [
    {
      "order": number (starts at 1, sequential),
      "title": string (short name for the action, under 60 characters),
      "body": string (one to two sentences explaining what to do and why it matters to customers, under 220 characters),
      "priority": "high" | "medium" | "low",
      "effort": "low" | "medium" | "high"
    }
  ]
}

Constraints:
- solution_map: maximum ${SOLUTION_MAP_MAX} items
- Order solution_map by priority first (high before low), then by effort (low before high)
- If owner intake context is provided, weave their language into the summary and the solution_map titles where it fits naturally
- The "issues" array is intentionally NOT requested back — the scan already produced authoritative issue data and we keep that as-is`
}

// ─── Output validation / normalisation ─────────────────────────────────

function finalizeReport(parsed: unknown): ReportOutput | null {
  if (typeof parsed !== 'object' || parsed === null) return null
  const obj = parsed as Record<string, unknown>

  const score = coerceHealthScore(obj.health_score)
  if (score === null) return null

  const summary =
    typeof obj.summary === 'string' ? obj.summary.trim() : ''
  if (!summary) return null

  if (!Array.isArray(obj.solution_map)) return null
  const steps: SolutionStep[] = []
  for (const raw of obj.solution_map) {
    if (steps.length >= SOLUTION_MAP_MAX) break
    const step = validateStep(raw, steps.length + 1)
    if (step) steps.push(step)
  }

  return { health_score: score, summary, solution_map: steps }
}

function coerceHealthScore(v: unknown): number | null {
  if (typeof v !== 'number' || Number.isNaN(v)) return null
  return Math.max(0, Math.min(100, Math.round(v)))
}

function validateStep(raw: unknown, fallbackOrder: number): SolutionStep | null {
  if (typeof raw !== 'object' || raw === null) return null
  const r = raw as Record<string, unknown>
  const title = typeof r.title === 'string' ? r.title.trim() : ''
  const body = typeof r.body === 'string' ? r.body.trim() : ''
  if (!title || !body) return null
  const priority = isPriority(r.priority) ? r.priority : 'medium'
  const effort = isEffort(r.effort) ? r.effort : 'medium'
  const order =
    typeof r.order === 'number' && Number.isFinite(r.order)
      ? Math.round(r.order)
      : fallbackOrder
  return { order, title, body, priority, effort }
}

function isPriority(v: unknown): v is 'high' | 'medium' | 'low' {
  return v === 'high' || v === 'medium' || v === 'low'
}

function isEffort(v: unknown): v is 'low' | 'medium' | 'high' {
  return v === 'low' || v === 'medium' || v === 'high'
}
